In [62]:
import numpy as np
import scipy.linalg as la
import sympy as sym
from scipy.optimize import minimize

In [2]:
matrix = [[1, 0, 1, 2], [2, 1, 4, 11], [3, 0, 3, 6], [4, 1, 6, 15]]

In [3]:
q,r = np.linalg.qr(matrix)

In [4]:
q

array([[-0.18257419,  0.2236068 ,  0.82454859,  0.48660692],
       [-0.36514837, -0.67082039,  0.40003314, -0.50659664],
       [-0.54772256,  0.67082039, -0.00816077, -0.4999334 ],
       [-0.73029674, -0.2236068 , -0.40003314,  0.50659664]])

In [5]:
r

array([[ -5.47722558e+00,  -1.09544512e+00,  -7.66811581e+00,
         -1.86225670e+01],
       [  0.00000000e+00,  -8.94427191e-01,  -1.78885438e+00,
         -6.26099034e+00],
       [  0.00000000e+00,   0.00000000e+00,  -1.02375271e-16,
         -1.07707511e-15],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         -6.72908534e-16]])

In [6]:
np.linalg.matrix_rank(matrix)

2

In [13]:
matrix = sym.Matrix([[1, 0, 1, 2], [2, 1, 4, 11], [3, 0, 3, 6], [4, 1, 6, 15]])

In [14]:
matrix.rref()

(Matrix([
 [1, 0, 1, 2],
 [0, 1, 2, 7],
 [0, 0, 0, 0],
 [0, 0, 0, 0]]), [0, 1])

In [15]:
matrix_solve = matrix = sym.Matrix([[1, 0, 1, 2, 5], [2, 1, 4, 11, 6], [3, 0, 3, 6, 7], [4, 1, 6, 15, 8]])

In [16]:
matrix_solve.rref()

(Matrix([
 [1, 0, 1, 2, 0],
 [0, 1, 2, 7, 0],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0]]), [0, 1, 4])

In [18]:
x = sym.Matrix([0, 0 , 1, 0])

In [20]:
x

Matrix([
[0],
[0],
[1],
[0]])

In [24]:
matrix = sym.Matrix([[1, 0, 1, 2], [2, 1, 4, 11], [3, 0, 3, 6], [4, 1, 6, 15]])

In [25]:
matrix.dot(x)

[1, 4, 3, 6]

In [34]:
matrix = np.array([[1, 0, 1, 2], [2, 1, 4, 11], [3, 0, 3, 6], [4, 1, 6, 15]])

In [40]:
answer = np.array([0, 1, 0, 1])

In [41]:
np.linalg.solve(matrix, answer)

LinAlgError: Singular matrix

In [37]:
a = np.array([[3,1], [1,2]])

In [38]:
b = np.array([9,8])

In [39]:
x = np.linalg.solve(a, b)

In [3]:
matrix = sym.Matrix([[1, 4, 2, 0], [2, 5, 1, 0], [3, 6, 0, 0]])

In [4]:
matrix.rref()

(Matrix([
 [1, 0, -2, 0],
 [0, 1,  1, 0],
 [0, 0,  0, 0]]), [0, 1])

In [5]:
matrix = sym.Matrix([[0, 1, 4, 0], [1, 2, -1, 0], [5, 8, 0, 0]])

In [6]:
matrix.rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0]]), [0, 1, 2])

In [7]:
matrix = sym.Matrix([[3, -4, -2], [0, 1, 1], [6, 7, 5]])

In [8]:
matrix.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), [0, 1, 2])

In [9]:
matrix = sym.Matrix([[-2, -5, 8, 0, -17], [1, 3, -5, 1, 5], [3, 11, -19, 7, 1], [1, 7, -13, 5, -3]])

In [10]:
matrix.rref()

(Matrix([
 [1, 0,  1, 0,  1],
 [0, 1, -2, 0,  3],
 [0, 0,  0, 1, -5],
 [0, 0,  0, 0,  0]]), [0, 1, 3])

In [14]:
A = sym.Matrix([[1, 0, 1, 2], [2, 1, 3, 11], [3, 0, 3, 6], [4, 1, 6, 15]])
x = sym.Matrix([1, 2, 1, 2])

In [15]:
A*x

Matrix([
[ 6],
[29],
[18],
[42]])

In [24]:
A_augmented = sym.Matrix([[1, 0, 1, 2, 1], [2, 1, 3, 11, 1], [3, 0, 3, 6, 1], [4, 1, 6, 15, 1]])

In [25]:
A_augmented.rref()

(Matrix([
 [1, 0, 0, 2, 0],
 [0, 1, 0, 7, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1]]), [0, 1, 2, 4])

In [26]:
v_1 = sym.Matrix([1, 2, 3, 4])
v_2 = sym.Matrix([0, 1, 0, 1])
v_3 = sym.Matrix([1, 4, 3, 6])
v_4 = sym.Matrix([2, 11, 6, 15])

In [29]:
matrix_1 = sym.Matrix([v_1, v_2, v_3])

In [30]:
matrix_1

Matrix([
[1],
[2],
[3],
[4],
[0],
[1],
[0],
[1],
[1],
[4],
[3],
[6]])

In [31]:
matrix_1 = sym.Matrix([[1, 0, 1, 2], [2, 1, 4, 11], [3, 0, 3, 6], [4, 1, 6, 15]])

In [32]:
matrix_1.rref()

(Matrix([
 [1, 0, 1, 2],
 [0, 1, 2, 7],
 [0, 0, 0, 0],
 [0, 0, 0, 0]]), [0, 1])

In [33]:
matrix_1 = sym.Matrix([[1, 0, 1], [2, 1, 4], [3, 0, 3], [4, 1, 6]])
matrix_1.rref()

(Matrix([
 [1, 0, 1],
 [0, 1, 2],
 [0, 0, 0],
 [0, 0, 0]]), [0, 1])

In [38]:
matrix_1 = sym.Matrix([[1, 1, 0], [2, 4, 1], [3, 3, 0], [4, 6, 1]])
matrix_1.rref()

(Matrix([
 [1, 0, -1/2],
 [0, 1,  1/2],
 [0, 0,    0],
 [0, 0,    0]]), [0, 1])

In [40]:
matrix_1 = sym.Matrix([[1, 0, 1, 2, 1], [2, 1, 4, 11, 3], [3, 0, 3, 6, 4], [4, 1, 6, 15, 5]])
matrix_1.rref()

(Matrix([
 [1, 0, 1, 2, 0],
 [0, 1, 2, 7, 0],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0]]), [0, 1, 4])

In [50]:
np_matrix = np.array([[1, 0, 1, 2], [2, 1, 4, 11], [3, 0, 3, 6], [4, 1, 6, 15]])

In [53]:
la.orth(np_matrix)

array([[-0.1098991 ,  0.2669373 ],
       [-0.54396107, -0.53613402],
       [-0.32969731,  0.80081189],
       [-0.76375927, -0.00225943]])

In [54]:
def con_1(t):
    return t[2] - (3 * t[0])

In [55]:
def con_2(t):
    b = t[1] - (2 * t[0])
    return t[3] - (4 * t[0]) - b

In [56]:
cons = [{'type':'eq', 'fun': con_1}, {'type':'eq', 'fun': con_2}]

In [59]:
def fun_to_minimize(t):
    z = np.array([1, 0, 0, 0])
    return np.linalg.norm(t - z)

In [61]:
fun_to_minimize(np.array([2, 1, 1, 1]))

2.0

In [63]:
x0 = np.array([1, 3, 3, 5])

In [64]:
res = minimize(fun_to_minimize, x0, constraints=cons)

In [65]:
res

     fun: 0.9574271081287898
     jac: array([-0.95743109, -0.087052  ,  0.26110456,  0.08701771])
 message: 'Optimization terminated successfully.'
    nfev: 26
     nit: 4
    njev: 4
  status: 0
 success: True
       x: array([ 0.08332953, -0.08334594,  0.24998858,  0.08331311])

In [66]:
sol = np.array([ 0.08332953, -0.08334594,  0.24998858,  0.08331311])

In [67]:
z = np.array([1, 0, 0, 0])
np.linalg.norm(sol - z)

0.95742710464702896

In [68]:
np.linalg.norm(x0 - z)

6.5574385243020004

In [69]:
test = np.array([0, 0, 0, 0])
np.linalg.norm(test - z)

1.0